// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg1': string;
  'bg2': string;
  'contentWrapper': string;
  'funBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
